# Generated by Django 6.0 on 2026-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='drop_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='load_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
